version: "3.9"

services:
  backend:
    build:
      context: ./ctf-frontend
      dockerfile: Dockerfile.backend
    container_name: level1
    ports:
      - "3000:3000"
    networks:
      - ctfnet

  frontend:
    build:
      context: ./ctf-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - ctfnet

networks:
  ctfnet:
